# Generated by Django 6.1 on 2026-09-25 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ar', models.CharField(max_length=200)),
                ('credit_hours', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('general', 'General'), ('cs', 'Computer Science'), ('it', 'Information Technology'), ('is', 'Information Systems'), ('ai', 'Artificial Intelligence')], max_length=20)),
                ('requirement_type', models.CharField(choices=[('compulsory', 'Compulsory'), ('elective', 'Elective')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('letter', models.CharField(max_length=5)),
                ('gpa_points', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('entry_year', models.PositiveIntegerField()),
                ('academic_level', models.PositiveIntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_hours_completed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn')], default='enrolled', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_score', models.PositiveIntegerField()),
                ('letter_grade', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_history', to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_history', to='academics.student')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='academics.course')),
                ('prerequisite_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='academics.course')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'prerequisite_course'), name='unique_course_prerequisite')],
            },
        ),
    ]
